//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorWebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vpsrv.visualset.com.br/PostagemVipp.asmx")]
        public string IntegradorWebService_WSVIPP_PostagemVipp {
            get {
                return ((string)(this["IntegradorWebService_WSVIPP_PostagemVipp"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vipp.visualset.com.br")]
        public string Site {
            get {
                return ((string)(this["Site"]));
            }
            set {
                this["Site"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PEFycmF5T2ZGb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvP" +
            "k9ic2VydmFjYW8xPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4xPC9Db2x1bmE+PC9Gb3JtYXRhY2FvUGxhb" +
            "mlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPlF1YW50aWRhZGU8L05vbWVBdHJpY" +
            "nV0bz48Q29sdW5hPjExPC9Db2x1bmE+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFua" +
            "WxoYT48Tm9tZUF0cmlidXRvPkNvbnRldWRvPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4xMDwvQ29sdW5hP" +
            "jwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5EZXN0a" +
            "W5hdGFyaW88L05vbWVBdHJpYnV0bz48Q29sdW5hPjE1PC9Db2x1bmE+PC9Gb3JtYXRhY2FvUGxhbmlsa" +
            "GE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPkRvY3VtZW50b0Rlc3RpbmF0YXJpbzwvT" +
            "m9tZUF0cmlidXRvPjxDb2x1bmE+MTY8L0NvbHVuYT48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0Y" +
            "WNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+RW5kZXJlY288L05vbWVBdHJpYnV0bz48Q29sdW5hPjE3P" +
            "C9Db2x1bmE+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlid" +
            "XRvPk51bWVybzwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MTg8L0NvbHVuYT48L0Zvcm1hdGFjYW9QbGFua" +
            "WxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+QmFpcnJvPC9Ob21lQXRyaWJ1dG8+P" +
            "ENvbHVuYT4xOTwvQ29sdW5hPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+P" +
            "E5vbWVBdHJpYnV0bz5Db21wbGVtZW50bzwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MjA8L0NvbHVuYT48L" +
            "0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Q0VQPC9Ob" +
            "21lQXRyaWJ1dG8+PENvbHVuYT4yMTwvQ29sdW5hPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY" +
            "2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5DaWRhZGU8L05vbWVBdHJpYnV0bz48Q29sdW5hPjIyPC9Db" +
            "2x1bmE+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvP" +
            "lVGPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4yMzwvQ29sdW5hPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb" +
            "3JtYXRhY2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5TZXJ2aWNvPC9Ob21lQXRyaWJ1dG8+PENvbHVuY" +
            "T4yNTwvQ29sdW5hPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjwvQXJyYXlPZkZvcm1hdGFjYW9QbGFuaWxoY" +
            "T4=")]
        public string Layout {
            get {
                return ((string)(this["Layout"]));
            }
            set {
                this["Layout"] = value;
            }
        }
    }
}
